name: Terraform Pipeline

on:
  push:
    branches:
      - dev
      - qa
      - main
      - rafiya

env:
  PROJECT_ID: project-586cba26-8a19-4658-b23
  REGION: us-central1
  REPOSITORY: Shaikirfan8/fashion-website

  SERVICE: login-service

jobs:
  Terraform-CI:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/1036679411770/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: terraform-sa@project-586cba26-8a19-4658-b23.iam.gserviceaccount.com
          permissions:
          id-token: write
          contents: read

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      # - name: Terraform Perform
      #   run: |
      #     cd fashionweb
      #     terraform init
      #     terraform validate
      #     terraform plan
      - name: Terraform Destroy
        run: |
          cd fashionweb
          terraform init
          terraform destroy --auto-approve
          
  Terraform-CD:
    needs: Terraform-CI
    runs-on: ubuntu-latest
  
    permissions:
      contents: read
      id-token: write
  
    steps:
      - uses: actions/checkout@v4
  
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6
  
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/1036679411770/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: terraform-sa@project-586cba26-8a19-4658-b23.iam.gserviceaccount.com
  
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
  
      - name: Terraform Init & Apply
        run: |
          cd fashionweb
          terraform init
          terraform apply -auto-approve
  
        # - name: Terraform Destroy
        #   run: |
        #     cd fashionweb
        #     terraform init
        #     terraform destroy --auto-approve
