name: Fashion Website Terraform Pipeline

on:
  workflow_dispatch:

env:
  PROJECT_ID: project-586cba26-8a19-4658-b23
  REGION: us-central1
  REPOSITORY: fashion-repo
  IMAGE: fashion-app
  SERVICE: fashion-service

jobs:
  terraform-ci:
    name: Terraform Validate & Plan
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/1036679411770/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: terraform-sa@project-586cba26-8a19-4658-b23.iam.gserviceaccount.com

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Terraform Init, Validate & Plan
        run: |
          cd fashionweb
          terraform init
          terraform validate
          terraform plan

  terraform-cd:
    name: Build Image & Deploy
    needs: terraform-ci
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/1036679411770/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: terraform-sa@project-586cba26-8a19-4658-b23.iam.gserviceaccount.com

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      # ðŸ”¥ Build Docker Image in Cloud (no local docker needed)
      - name: Build & Push Docker Image
        run: |
          gcloud builds submit \
            --tag ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:latest

      # ðŸ”¥ Terraform Apply (Deploy Cloud Run)
      - name: Terraform Apply
        run: |
          cd fashionweb
          terraform init
          terraform apply -auto-approve
