name: Deploy Login App

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: project-66a29879-9843-4202-83c
  REGION: us-central1
  REPOSITORY: Shaikirfan8/fashion-website

  SERVICE: login-service

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/904849386006/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: terraform-sa@project-66a29879-9843-4202-83c.iam.gserviceaccount.com

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build Image
        run: |
          docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/login:${{ github.sha }} ./login-app

      - name: Push Image
        run: |
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/login:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE }} \
            --image=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/login:${{ github.sha }} --region=${{ env.REGION }} --platform=managed --allow-unauthenticated
